--식집사 119 DB

-- 회원 테이블 생성
CREATE TABLE "PLANT_MEMBER" (
	
	"MEMBER_NO" NUMBER PRIMARY KEY,
	"MEMBER_ID" VARCHAR2(30) NOT NULL,
	"MEMBER_PW" VARCHAR2(100) NOT NULL,
	"MEMBER_NAME" VARCHAR2(10) NOT NULL,
	"MEMBER_NICKNAME" VARCHAR2(10) NOT NULL UNIQUE,
	"MEMBER_ADDRESS" VARCHAR2(200) NOT NULL,
	"MEMBER_TEL" CHAR(11) NOT NULL,
	
	"PROFILE_IMG" VARCHAR2(300),
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL" CHAR(1) DEFAULT 'N'
		CHECK("MEMBER_DEL_FL" IN('Y', 'N')),
	"AUTHORITY" NUMBER DEFAULT 1 CHECK("AUTHORITY" IN (1,2))
); 

 DROP TABLE "PLANT_MEMBER";

-- 코멘트 설정
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_NO" IS '회원 번호(SEQ)';
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_PW" IS '회원 비밀번호(암호화)';
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_NAME" IS '회원 이름';
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_ADDRESS" IS '회원 주소';
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_TEL" IS '회원 전화번호(-없음)';

COMMENT ON COLUMN "PLANT_MEMBER"."PROFILE_IMG" IS '프로필 이미지';
COMMENT ON COLUMN "PLANT_MEMBER"."ENROLL_DATE" IS '회원가입일';
COMMENT ON COLUMN "PLANT_MEMBER"."MEMBER_DEL_FL" IS '탈퇴 여부(Y:정상, N:탈퇴)';
COMMENT ON COLUMN "PLANT_MEMBER"."AUTHORITY" IS '관리자 권한(1: 회원, 2:관리자)';


-- 시퀀싱 설정
CREATE SEQUENCE SEQ_PLANT_MEMBER_NO NOCACHE;


-- 샘플 계정 추가
INSERT INTO PLANT_MEMBER
VALUES (SEQ_PLANT_MEMBER_NO.NEXTVAL, 'lani', '1234', '예리나', '테스트', '04187^^^서울시 서대문구^^^1동',
	'01011111111', NULL, DEFAULT, DEFAULT, DEFAULT);
COMMIT;


