-- 01. example, example2 계정 생성, 권한 추가

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER example IDENTIFIED BY "921222"; -- example 계정생성
GRANT CONNECT, RESOURCE, CREATE SESSION TO example; -- 개채생성, 변경, 제거권한, 접속권한 
ALTER USER example DEFAULT TABLESPACE "A230724"
QUOTA 10M ON "A230724";

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER example2 IDENTIFIED BY "921222"; -- example2 계정생성
GRANT CONNECT, CREATE VIEW TO example2; -- DB접속권한, 뷰 생성권한 추가 

--------------------------------------------------------

-- 02. example2 계정 DB연결 권한 회수 후 계정 삭제

REVOKE CONNECT FROM example2;
DROP USER example2 CASCADE; 


--------------------------------------------------------

-- 03. example 계정에서 MEMBER 테이블과 BOARD 테이블을 생성

-- MEMBER TABLE 생성
CREATE TABLE MEMBER(
	
	MEMBER_NO		NUMBER PRIMARY KEY,
	MEMBER_ID 		VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
	PHONE_NUMBER 	VARCHAR2(20),
	DELETE_YN		CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN ('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN IS '삭제여부';


-- BOARD TABLE 생성
CREATE TABLE BOARD (
	
	BOARD_NO	  NUMBER PRIMARY KEY,
	BOARD_TITLE   VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER  NUMBER REFERENCES MEMBER(MEMBER_NO),
	CREATE_DATE   DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일자';


--------------------------------------------------------

-- 04. MEMBER 테이블과 BOARD 테이블 데이터 추가

-- MEMBER 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 100;

-- BOARD 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD_NO;


-- MEMBER 테이블 데이터 추가
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'step1', 'step11', '-');

INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'step2', 'step22', '010-1111-2222');

INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'step3', 'step33', '-');

-- MEMBER 테이블 추가된 데이터 조회
SELECT MEMBER_NO "회원번호", MEMBER_ID "아이디", MEMBER_PASSWORD "비밀번호", PHONE_NUMBER "전화번호"
FROM MEMBER
ORDER BY MEMBER_NO;



-- BOARD 테이블 데이터 추가
INSERT INTO BOARD
VALUES (SEQ_BOARD_NO.NEXTVAL, '첫 글', '스텝평가', 100, DEFAULT);

INSERT INTO BOARD
VALUES (SEQ_BOARD_NO.NEXTVAL, '두 번째 글', '재밌다', 300, DEFAULT);

INSERT INTO BOARD
VALUES (SEQ_BOARD_NO.NEXTVAL, '세 번째 글', '하하하', 200, DEFAULT);


-- MEMBER 테이블 추가된 데이터 조회
SELECT BOARD_NO "글번호", BOARD_TITLE "글제목", BOARD_CONTENT "글내용", BOARD_WRITER "작성자번호", CREATE_DATE "작성일자"
FROM BOARD
ORDER BY BOARD_NO;


--------------------------------------------------------

-- 05. SELECT문 작성

SELECT BOARD_NO "글번호", BOARD_TITLE "제목", BOARD_CONTENT "내용", MEMBER_ID "작성자", CREATE_DATE "작성일자"
FROM BOARD
JOIN MEMBER ON (MEMBER_NO = BOARD_WRITER)
ORDER BY BOARD_NO DESC;

