-- 키워드 저장 테이블 생성
CREATE TABLE YS_KEYWORD (
	KEY_NO		NUMBER CONSTRAINT PK PRIMARY KEY,
	KEY_NAME	VARCHAR2(40) CONSTRAINT KEY_NAME_NN NOT NULL,
	KEY_COUNT	NUMBER CONSTRAINT KEY_COUNT_NN NOT NULL,
	KEY_TAG		NUMBER DEFAULT 1 CONSTRAINT KEY_TAG_NN NOT NULL,
	KEY_RESULT	VARCHAR2(50) CONSTRAINT KEY_RESULT_NN NOT NULL,
	INDEX_CODE	CHAR(2) CONSTRAINT INDEX_CODE_NN NOT NULL,
	
	CONSTRAINT KEY_NAME_U UNIQUE(KEY_NAME),
	CONSTRAINT KEY_TAG_CHECK CHECK(KEY_TAG IN (1, 0)),
	CONSTRAINT INDEX_CODE_FK FOREIGN KEY(INDEX_CODE) REFERENCES YS_INDEX
	
);

COMMENT ON COLUMN YS_KEYWORD.KEY_NO IS '키워드넘버';
COMMENT ON COLUMN YS_KEYWORD.KEY_NAME IS '키워드명';
COMMENT ON COLUMN YS_KEYWORD.KEY_COUNT IS '키워드 갯수';
COMMENT ON COLUMN YS_KEYWORD.KEY_TAG IS '키워드 태그 유무(있으면 1, 없으면 0)';
COMMENT ON COLUMN YS_KEYWORD.KEY_RESULT IS '순위';
COMMENT ON COLUMN YS_KEYWORD.INDEX_CODE IS '범주';



-- 인덱스 테이블 생성
CREATE TABLE YS_INDEX (
	INDEX_CODE CHAR(2) PRIMARY KEY,
	INDEX_TITLE VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN YS_INDEX.INDEX_CODE IS '인덱스 번호';
COMMENT ON COLUMN YS_INDEX.INDEX_TITLE IS '인덱스명';


----------------------------------------------------------------


INSERT INTO YS_INDEX
VALUES ('I1', '메인 키워드');

INSERT INTO YS_INDEX
VALUES ('I2', '서브 키워드');

INSERT INTO YS_INDEX
VALUES ('I3', '죽은 키워드');

INSERT INTO YS_INDEX
VALUES ('I4', '애매한 키워드');

SELECT * FROM YS_INDEX ;


----------------------------------------------------------------

-- KEYWORD 컬럼값 입력
SELECT * FROM YS_KEYWORD;
DELETE FROM YS_KEYWORD;


INSERT INTO YS_KEYWORD VALUES (1, '여자정수리탈모', 7, 0, '망/망/망', 'I1');
INSERT INTO YS_KEYWORD VALUES (2, '모발이식생착기간', 7, 1, '7/6/2', 'I1');
INSERT INTO YS_KEYWORD VALUES (3, '절개모발이식비용', 2, 0, '굿/7', 'I1');
INSERT INTO YS_KEYWORD VALUES (4, '모발이식방법', 2, 0, '망/17/27/21/9', 'I1');
INSERT INTO YS_KEYWORD VALUES (5, '여성정수리탈모', 1, 0, '17/망/6/12', 'I1');
INSERT INTO YS_KEYWORD VALUES (6, '모발이식생착률', 7, 1, '망/32/25/망/망', 'I1');
INSERT INTO YS_KEYWORD VALUES (7, '절개모발이식', 2, 0, '14/6/17', 'I1');
INSERT INTO YS_KEYWORD VALUES (8, '여자모발이식비용', 8, 1, '1/망/3/망/4', 'I1');
INSERT INTO YS_KEYWORD VALUES (9, '헤어라인모발이식비용', 9, 1, '6/망/4/2', 'I1');
INSERT INTO YS_KEYWORD VALUES (10, '모발이식절개', 12, 1, '6/5/20/10', 'I1');
INSERT INTO YS_KEYWORD VALUES (11, '정수리모발이식비용', 3, 0, '굿/7/2', 'I1');
INSERT INTO YS_KEYWORD VALUES (12, '여성모발이식비용', 2, 0, '7/망/1/4', 'I1');
INSERT INTO YS_KEYWORD VALUES (13, '모발이식절개비절개', 7, 1, '망/17/7/16/19', 'I1');
INSERT INTO YS_KEYWORD VALUES (14, '비절개모발이식비용', 4, 0, '망/10/21', 'I1');
INSERT INTO YS_KEYWORD VALUES (15, '앞머리모발이식비용', 10, 1, '굿/굿/2', 'I1');
INSERT INTO YS_KEYWORD VALUES (16, '비절개모발이식가격', 1, 0, '망/망/20', 'I1');
INSERT INTO YS_KEYWORD VALUES (17, '비절개모발이식후기', 3, 0, '망/망/10/9/14', 'I1');
INSERT INTO YS_KEYWORD VALUES (18, '비절개모발이식수술', 7, 1, '8/망/5/9/10', 'I1');












