-- 회원, 게시판, 댓글 테이블 기술서
-- 1) MEMBER 테이블 삭제하고 진행하기
-- 2) "COMMENT" -> COMMENT 테이블명 작성 시 " " (쌍따옴표)로 꼭 감싸기

DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	MEMBER_NO 		NUMBER PRIMARY KEY,
	MEMBER_EMAIL 	VARCHAR2(50)  NOT NULL,
	MEMBER_PW 		VARCHAR2(100)  NOT NULL,
	MEMBER_NICKNAME VARCHAR2(30)  NOT NULL,
	MEMBER_TEL 		CHAR(11)  NOT NULL,
	MEMBER_ADDRESS  VARCHAR2(300),
	ENROLL_DATE 	DATE DEFAULT SYSDATE NOT NULL,
	MEMBER_DEL_FL   CHAR(1) DEFAULT 'N'  NOT NULL,
	
	CHECK(MEMBER_DEL_FL IN ('N', 'Y'))
);

SELECT * FROM MEMBER;

COMMENT ON COLUMN MEMBER.MEMBER_NO 	     IS '회원 번호';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL	 IS '회원 이메일';
COMMENT ON COLUMN MEMBER.MEMBER_PW 		 IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NICKNAME IS '회원 닉네임';
COMMENT ON COLUMN MEMBER.MEMBER_TEL 	 IS '휴대폰 번호(- 없음)';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS  IS '회원 주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE 	 IS '회원 가입일';
COMMENT ON COLUMN MEMBER.MEMBER_DEL_FL 	 IS '탈퇴여부(N : 탈퇴X , Y : 탈퇴 O)';


CREATE TABLE BOARD (

BOARD_NO 	  NUMBER PRIMARY KEY,
BOARD_TITLE   VARCHAR2(150)  NOT NULL,
BOARD_CONTENT VARCHAR2(4000) NOT NULL,
B_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
READ_COUNT    NUMBER DEFAULT 0 NOT NULL,
BOARD_DEL_FL  CHAR(1) DEFAULT 'N' NOT NULL,
MEMBER_NO 	  NUMBER NOT NULL,

CHECK(BOARD_DEL_FL IN ('N', 'Y')),
FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER
);

COMMENT ON COLUMN BOARD.BOARD_NO 	  IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE   IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.B_CREATE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.READ_COUNT	  IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_DEL_FL  IS '삭제 여부(N : 삭제X , Y : 삭제O)';
COMMENT ON COLUMN BOARD.MEMBER_NO	  IS '작성자 회원 번호';



CREATE TABLE "COMMENT" (

COMMENT_NO		NUMBER PRIMARY KEY,
COMMENT_CONTENT VARCHAR2(4000) NOT NULL,
C_CREATE_DATE 	DATE DEFAULT SYSDATE NOT NULL,
COMMENT_DEL_FL  CHAR(1) DEFAULT 'N' NOT NULL,
BOARD_NO		NUMBER NOT NULL,
MEMBER_NO 		NUMBER NOT NULL,

CHECK(COMMENT_DEL_FL IN ('N', 'Y')),
FOREIGN KEY(BOARD_NO) REFERENCES BOARD,
FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER

);

COMMENT ON COLUMN "COMMENT".COMMENT_NO IS '댓글 번호';
COMMENT ON COLUMN "COMMENT".COMMENT_CONTENT IS '댓글 내용';
COMMENT ON COLUMN "COMMENT".C_CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN "COMMENT".COMMENT_DEL_FL IS '댓글 삭제 여부(N : 삭제X, Y : 삭제O)';
COMMENT ON COLUMN "COMMENT".BOARD_NO IS '댓글이 작성된 게시글 번호';
COMMENT ON COLUMN "COMMENT".MEMBER_NO IS '댓글 작성자 회원 번호';

COMMIT;
