-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시글번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; --댓글번호


-- MEMBER 테이블에 INSERT 하기
INSERT INTO MEMBER
VALUES (SEQ_MEMBER_NO.NEXTVAL,
	'mem01@naver.com',
	'1234',
	'1번회원',
	'0103825',
	'서울시 중구 어쩌구',
	DEFAULT, DEFAULT);
	
COMMIT;


SELECT * FROM MEMBER;


--		// 이메일, 비밀번호가 일치하는 회원의
--		// 닉네임, 전화번호, 주소를 수정
--		// (아이디 중복 없다고 가정)

UPDATE MEMBER
SET MEMBER_NICKNAME = '변경된 닉네임' ,
MEMBER_TEL = '010101010',
MEMBER_ADDRESS = '부산 해운대구'
WHERE MEMBER_EMAIL = 'mem01@naver.com'
AND MEMBER_PW = '1234'
;

ROLLBACK;
		


DELETE FROM MEMBER
WHERE MEMBER_EMAIL = 'mem01@naver.com'
AND MEMBER_PW = '1234';



UPDATE MEMBER
SET MEMBER_PW = '4321'
WHERE MEMBER_EMAIL = 'mem01@naver.com'
AND MEMBER_PW = '1234';


-- 로그인
SELECT MEMBER_NO , MEMBER_NICKNAME , MEMBER_TEL , MEMBER_ADDRESS ,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM MEMBER
WHERE MEMBER_EMAIL = 'mem01@naver.com'
AND MEMBER_PW = '4321'
AND MEMBER_DEL_FL = 'N';


--멤버테이블 전체조회
SELECT * FROM MEMBER
ORDER BY MEMBER_NO;

SELECT * FROM MEMBER
ORDER BY MEMBER_NO DESC;



SELECT * FROM MEMBER ORDER BY MEMBER_NO DESC;



--닉네임, 전화번호 수정
UPDATE MEMBER SET
MEMBER_NICKNAME = '라니',
MEMBER_TEL = '0106534'
WHERE MEMBER_NO = 4;


-- 회원 탈퇴
UPDATE MEMBER SET
MEMBER_DEL_FL = 'Y'
WHERE MEMBER_NO = 3
AND MEMBER_PW = '4321'
;


COMMIT;

--BOARD 테이블에 INSERT 하기
--실행 후 COMMIT/ROLLBACK 무조건 수행

INSERT INTO BOARD
VALUES (SEQ_BOARD_NO.NEXTVAL, '제목', '내용', DEFAULT, 
DEFAULT, DEFAULT, 회원번호)
;


DELETE FROM BOARD;


UPDATE MEMBER
SET MEMBER_DEL_FL = 'N';

COMMIT;


-----------------------------------------------------
-- FOR CARAT MEMBER, BOARD, COMMENT 테이블 만들기 ㅋㅋㅋㅋㅋㅋㅋ

--CREATE CARAT_MEMBER(
--
--	CMEMBER_NO NUMBER PRIMARY KEY,
--	CMEMBER_ID VARCHAR2(50) NOT NULL,
--	CMEMBER_PW VARCHAR2(100) NOT NULL,
--	CMEMBER_NICKNAME VARCHAR2(30) NOT NULL,
--	CMEMBER_TEL CHAR(11) NOT NULL,
--	CMEMBER_ADDRESS VARCHAR2(300),
--	CENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
--	CMEMBER_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL,
--	
--	CHECK(CMEMBER_DEL_FL IN ('N', 'Y'))
--);


-- 게시글 목록 조회(작성자 닉네임 포함)
-- 1) 삭제되지 않은 글
-- 2) 최신글 순(BOARD_NO 내림차순)
SELECT BOARD_NO, BOARD_TITLE, 
	TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') B_CREATE_DATE,
	READ_COUNT, MEMBER_NO, MEMBER_NICKNAME 
FROM BOARD 
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;


SELECT BOARD_NO , BOARD_TITLE , TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') B_CREATE_DATE,
	READ_COUNT , MEMBER_NO , MEMBER_NICKNAME 
FROM BOARD
JOIN MEMBER USING (MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC
;



COMMIT;



-- 회원 정보 수정

UPDATE MEMBER
SET MEMBER_NICKNAME = '',
MEMBER_TEL = ''
WHERE MEMBER_NO = ;



UPDATE MEMBER
SET MEMBER_DEL_FL = 'N';

SELECT * FROM MEMBER
ORDER BY MEMBER_NO DESC;










